##
## This file was generated by Google::ProtocolBuffers (0.08_01)
## on Thu Nov 21 19:51:12 2013 from file ../ICSG-v1_7-2007.proto
##
package ICSG_v1_7_2007_pb2;
use strict;
use warnings;
use Google::ProtocolBuffers;
{
    unless (CIF::ICSG::Relationship::RelationshipTypeEnum->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'CIF::ICSG::Relationship::RelationshipTypeEnum',
            [
               ['RelationshipTypeEnum_causesToInstall', 1],
               ['RelationshipTypeEnum_contactedBy', 2],
               ['RelationshipTypeEnum_downloadedFrom', 3],
               ['RelationshipTypeEnum_downloads', 4],
               ['RelationshipTypeEnum_hasAssociatedConfiguration', 5],
               ['RelationshipTypeEnum_hosts', 6],
               ['RelationshipTypeEnum_installed', 7],
               ['RelationshipTypeEnum_isClassifiedAs', 8],
               ['RelationshipTypeEnum_isNameServerOf', 9],
               ['RelationshipTypeEnum_isParentOf', 10],
               ['RelationshipTypeEnum_isServerOfService', 11],
               ['RelationshipTypeEnum_operatedByEntity', 12],
               ['RelationshipTypeEnum_relatedTo', 13],
               ['RelationshipTypeEnum_resolvesTo', 14],
               ['RelationshipTypeEnum_runs', 15],
               ['RelationshipTypeEnum_usesCNC', 16],
               ['RelationshipTypeEnum_verifiedBy', 17],

            ]
        );
    }
    
    unless (CIF::ICSG::Property::PropertyTypeEnum->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'CIF::ICSG::Property::PropertyTypeEnum',
            [
               ['PropertyTypeEnum_adminContact', 1],
               ['PropertyTypeEnum_browser', 2],
               ['PropertyTypeEnum_city', 3],
               ['PropertyTypeEnum_comment', 4],
               ['PropertyTypeEnum_countryCodeFIPS', 5],
               ['PropertyTypeEnum_countryCodeISO3166_2', 6],
               ['PropertyTypeEnum_countryCodeISO3166_3', 7],
               ['PropertyTypeEnum_filename', 8],
               ['PropertyTypeEnum_filepath', 9],
               ['PropertyTypeEnum_httpMethod', 10],
               ['PropertyTypeEnum_isDamaged', 11],
               ['PropertyTypeEnum_isKernel', 12],
               ['PropertyTypeEnum_isNonReplicating', 13],
               ['PropertyTypeEnum_isParasitic', 14],
               ['PropertyTypeEnum_isPolymorphic', 15],
               ['PropertyTypeEnum_isStealth', 16],
               ['PropertyTypeEnum_isVirus', 17],
               ['PropertyTypeEnum_isp', 18],
               ['PropertyTypeEnum_locationUrl', 19],
               ['PropertyTypeEnum_nameServer', 20],
               ['PropertyTypeEnum_operatingSystem', 21],
               ['PropertyTypeEnum_ownerAddress', 22],
               ['PropertyTypeEnum_postData', 23],
               ['PropertyTypeEnum_referrer', 24],
               ['PropertyTypeEnum_region', 25],
               ['PropertyTypeEnum_registrant', 26],
               ['PropertyTypeEnum_registrationDate', 27],
               ['PropertyTypeEnum_registryValueData', 28],
               ['PropertyTypeEnum_technicalContact', 29],
               ['PropertyTypeEnum_urlParameterString', 30],
               ['PropertyTypeEnum_userAgent', 31],

            ]
        );
    }
    
    unless (CIF::ICSG::ClassificationObject::ClassificationTypeEnum->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'CIF::ICSG::ClassificationObject::ClassificationTypeEnum',
            [
               ['ClassificationTypeEnum_clean', 1],
               ['ClassificationTypeEnum_dirty', 2],
               ['ClassificationTypeEnum_neutral', 3],
               ['ClassificationTypeEnum_unknown', 4],
               ['ClassificationTypeEnum_unwanted', 5],

            ]
        );
    }
    
    unless (CIF::ICSG::LocationType::LocationTypeEnum->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'CIF::ICSG::LocationType::LocationTypeEnum',
            [
               ['LocationTypeEnum_city', 1],
               ['LocationTypeEnum_countryCodeFIPS', 2],
               ['LocationTypeEnum_countryCodeISO3166_2', 3],
               ['LocationTypeEnum_countryCodeISO3166_3', 4],
               ['LocationTypeEnum_isp', 5],
               ['LocationTypeEnum_region', 6],

            ]
        );
    }
    
    unless (CIF::ICSG::IPAddress::IPTypeEnum->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'CIF::ICSG::IPAddress::IPTypeEnum',
            [
               ['IPTypeEnum_ipv4', 1],
               ['IPTypeEnum_ipv6', 2],

            ]
        );
    }
    
    unless (CIF::ICSG::FieldDataEntry::OriginTypeEnum->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'CIF::ICSG::FieldDataEntry::OriginTypeEnum',
            [
               ['OriginTypeEnum_collection', 1],
               ['OriginTypeEnum_desktop', 2],
               ['OriginTypeEnum_gateway', 3],
               ['OriginTypeEnum_honeypot', 4],
               ['OriginTypeEnum_internal', 5],
               ['OriginTypeEnum_isp', 6],
               ['OriginTypeEnum_lan', 7],
               ['OriginTypeEnum_partner', 8],
               ['OriginTypeEnum_spam', 9],
               ['OriginTypeEnum_unknown', 10],
               ['OriginTypeEnum_user', 11],
               ['OriginTypeEnum_wan', 12],

            ]
        );
    }
    
    unless (CIF::ICSG::VolumeType::VolumeUnitsEnum->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'CIF::ICSG::VolumeType::VolumeUnitsEnum',
            [
               ['VolumeUnitsEnum_numberMachinesAffected', 1],
               ['VolumeUnitsEnum_numberOfWebsitesHosting', 2],
               ['VolumeUnitsEnum_numberOfWebsitesRedirecting', 3],
               ['VolumeUnitsEnum_numberSeenInMalwareSamples', 4],
               ['VolumeUnitsEnum_numberSeenInSpam', 5],
               ['VolumeUnitsEnum_numberUsersAffected', 6],

            ]
        );
    }
    
    unless (CIF::ICSG::LocationType->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::ICSG::LocationType',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'CIF::ICSG::LocationType::LocationTypeEnum', 
                    'type', 1, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::ICSG::ClassificationObject->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::ICSG::ClassificationObject',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'classificationName', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'companyName', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'category', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::ICSG::ClassificationDetailsType', 
                    'classificationDetails', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::ICSG::ClassificationObject::ClassificationTypeEnum', 
                    'type', 5, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'id', 6, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::ICSG::TargetType->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::ICSG::TargetType',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::ICSG::Reference', 
                    'ref', 1, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::ICSG::Property->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::ICSG::Property',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::ICSG::Property::PropertyTypeEnum', 
                    'type', 1, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::ICSG::DomainObject->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::ICSG::DomainObject',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'domain', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'id', 2, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::ICSG::UriObject->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::ICSG::UriObject',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'uriString', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'protocol', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'hostname', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'domain', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'port', 5, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'path', 6, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'ipProtocol', 7, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'id', 8, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::ICSG::FieldDataEntry->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::ICSG::FieldDataEntry',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::ICSG::ReferencesType', 
                    'references', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT64(), 
                    'startDate', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT64(), 
                    'endDate', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT64(), 
                    'firstSeenDate', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::ICSG::FieldDataEntry::OriginTypeEnum', 
                    'origin', 5, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'commonality', 6, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::ICSG::VolumeType', 
                    'volume', 7, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'importance', 8, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::ICSG::LocationType', 
                    'location', 9, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::ICSG::ObjectProperty->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::ICSG::ObjectProperty',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::ICSG::ReferencesType', 
                    'references', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT64(), 
                    'timestamp', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::ICSG::Property', 
                    '_property', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'CIF::ICSG::UnspecifiedType', 
                    'id', 4, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::ICSG::VolumeType->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::ICSG::VolumeType',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::ICSG::VolumeType::VolumeUnitsEnum', 
                    'units', 1, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::ICSG::SourceType->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::ICSG::SourceType',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::ICSG::Reference', 
                    'ref', 1, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::ICSG::MalwareMetaDataType->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::ICSG::MalwareMetaDataType',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_DOUBLE(), 
                    'version', 1, 20120628
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'company', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'author', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'comment', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT64(), 
                    'timestamp', 5, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::ICSG::ObjectsType', 
                    'objects', 6, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::ICSG::ObjectPropertiesType', 
                    'objectProperties', 7, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::ICSG::RelationshipsType', 
                    'relationships', 8, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::ICSG::FieldDataType', 
                    'fieldData', 9, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'id', 10, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::ICSG::ExtraHashType->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::ICSG::ExtraHashType',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'type', 1, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::ICSG::EntityObject->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::ICSG::EntityObject',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'name', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'id', 2, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::ICSG::RelationshipsType->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::ICSG::RelationshipsType',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::ICSG::Relationship', 
                    '_relationship', 1, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::ICSG::ObjectPropertiesType->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::ICSG::ObjectPropertiesType',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::ICSG::ObjectProperty', 
                    '_objectProperty', 1, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::ICSG::Reference->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::ICSG::Reference',
            [

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::ICSG::IPAddress->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::ICSG::IPAddress',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::ICSG::IPAddress::IPTypeEnum', 
                    'type', 1, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::ICSG::RegistryObject->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::ICSG::RegistryObject',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'key', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'valueName', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'id', 3, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::ICSG::FieldDataType->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::ICSG::FieldDataType',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::ICSG::FieldDataEntry', 
                    '_fieldDataEntry', 1, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::ICSG::ClassificationDetailsType->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::ICSG::ClassificationDetailsType',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'definitionVersion', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT64(), 
                    'detectionAddedTimeStamp', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT64(), 
                    'detectionShippedTimeStamp', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'product', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'productVersion', 5, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::ICSG::ObjectsType->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::ICSG::ObjectsType',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::ICSG::FileObject', 
                    'file', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::ICSG::UriObject', 
                    'uri', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::ICSG::DomainObject', 
                    'domain', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::ICSG::RegistryObject', 
                    'registry', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::ICSG::IPObject', 
                    'ip', 5, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::ICSG::ASNObject', 
                    'asn', 6, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::ICSG::EntityObject', 
                    'entity', 7, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::ICSG::ClassificationObject', 
                    'classification', 8, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::ICSG::ReferencesType->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::ICSG::ReferencesType',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::ICSG::Reference', 
                    'ref', 1, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::ICSG::UnspecifiedType->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::ICSG::UnspecifiedType',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'baseObjectType', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_BYTES(), 
                    'object', 2, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::ICSG::IPObject->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::ICSG::IPObject',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::ICSG::IPAddress', 
                    'startAddress', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::ICSG::IPAddress', 
                    'endAddress', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'id', 3, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::ICSG::ASNObject->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::ICSG::ASNObject',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'as_number', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'id', 2, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::ICSG::Relationship->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::ICSG::Relationship',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::ICSG::SourceType', 
                    'source', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::ICSG::TargetType', 
                    'target', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT64(), 
                    'timestamp', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::ICSG::Relationship::RelationshipTypeEnum', 
                    'type', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'CIF::ICSG::UnspecifiedType', 
                    'id', 5, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::ICSG::FileObject->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::ICSG::FileObject',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'md5', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'sha1', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'sha256', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'sha512', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'size', 5, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'crc32', 6, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'fileType', 7, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::ICSG::ExtraHashType', 
                    'extraHash', 8, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'id', 9, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

}
1;
