##
## This file was generated by Google::ProtocolBuffers (0.08_01)
## on Thu Nov 21 19:51:13 2013 from file ../MAEC-v2.proto
##
package MAEC_v2_pb2;
use strict;
use warnings;
use Google::ProtocolBuffers;
{
    unless (CIF::MAEC::MaecPlaceholder->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::MAEC::MaecPlaceholder',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_DOUBLE(), 
                    'version', 1, 20120628
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'msg', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'i', 3, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

}
1;
