##
## This file was generated by Google::ProtocolBuffers (0.08_01)
## on Thu Nov 21 19:51:13 2013 from file ../RFC4765-IDMEF-2007.proto
##
package RFC4765_IDMEF_2007_pb2;
use strict;
use warnings;
use Google::ProtocolBuffers;
{
    unless (CIF::IDMEF::Impact::ImpactCompletion->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'CIF::IDMEF::Impact::ImpactCompletion',
            [
               ['impact_completion_failed', 1],
               ['impact_completion_succeeded', 2],

            ]
        );
    }
    
    unless (CIF::IDMEF::Source::YesNoType->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'CIF::IDMEF::Source::YesNoType',
            [
               ['yes_no_type_no', 1],
               ['yes_no_type_unknown', 2],
               ['yes_no_type_yes', 3],

            ]
        );
    }
    
    unless (CIF::IDMEF::Reference::ReferenceOrigin->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'CIF::IDMEF::Reference::ReferenceOrigin',
            [
               ['reference_origin_bugtraqid', 1],
               ['reference_origin_cve', 2],
               ['reference_origin_osvdb', 3],
               ['reference_origin_unknown', 4],
               ['reference_origin_user_specific', 5],
               ['reference_origin_vendor_specific', 6],

            ]
        );
    }
    
    unless (CIF::IDMEF::File::FileCategory->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'CIF::IDMEF::File::FileCategory',
            [
               ['file_category_current', 1],
               ['file_category_original', 2],

            ]
        );
    }
    
    unless (CIF::IDMEF::Address::AddressCategory->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'CIF::IDMEF::Address::AddressCategory',
            [
               ['address_category_atm', 1],
               ['address_category_e_mail', 2],
               ['address_category_ipv4_addr', 3],
               ['address_category_ipv4_addr_hex', 4],
               ['address_category_ipv4_net', 5],
               ['address_category_ipv4_net_mask', 6],
               ['address_category_ipv6_addr', 7],
               ['address_category_ipv6_addr_hex', 8],
               ['address_category_ipv6_net', 9],
               ['address_category_ipv6_net_mask', 10],
               ['address_category_lotus_notes', 11],
               ['address_category_mac', 12],
               ['address_category_sna', 13],
               ['address_category_unknown', 14],
               ['address_category_vm', 15],

            ]
        );
    }
    
    unless (CIF::IDMEF::Node::NodeCategory->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'CIF::IDMEF::Node::NodeCategory',
            [
               ['node_category_ads', 1],
               ['node_category_afs', 2],
               ['node_category_coda', 3],
               ['node_category_dfs', 4],
               ['node_category_dns', 5],
               ['node_category_hosts', 6],
               ['node_category_kerberos', 7],
               ['node_category_nds', 8],
               ['node_category_nis', 9],
               ['node_category_nisplus', 10],
               ['node_category_nt', 11],
               ['node_category_unknown', 12],
               ['node_category_wfw', 13],

            ]
        );
    }
    
    unless (CIF::IDMEF::Impact::ImpactSeverity->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'CIF::IDMEF::Impact::ImpactSeverity',
            [
               ['impact_severity_high', 1],
               ['impact_severity_info', 2],
               ['impact_severity_low', 3],
               ['impact_severity_medium', 4],

            ]
        );
    }
    
    unless (CIF::IDMEF::User::UserCategory->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'CIF::IDMEF::User::UserCategory',
            [
               ['user_category_application', 1],
               ['user_category_os_device', 2],
               ['user_category_unknown', 3],

            ]
        );
    }
    
    unless (CIF::IDMEF::UserId::IdType->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'CIF::IDMEF::UserId::IdType',
            [
               ['id_type_current_group', 1],
               ['id_type_current_user', 2],
               ['id_type_group_privs', 3],
               ['id_type_original_user', 4],
               ['id_type_other_privs', 5],
               ['id_type_target_user', 6],
               ['id_type_user_privs', 7],

            ]
        );
    }
    
    unless (CIF::IDMEF::Confidence::ConfidenceRating->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'CIF::IDMEF::Confidence::ConfidenceRating',
            [
               ['confidence_rating_high', 1],
               ['confidence_rating_low', 2],
               ['confidence_rating_medium', 3],
               ['confidence_rating_numeric', 4],

            ]
        );
    }
    
    unless (CIF::IDMEF::Impact::ImpactType->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'CIF::IDMEF::Impact::ImpactType',
            [
               ['impact_type_admin', 1],
               ['impact_type_dos', 2],
               ['impact_type_file', 3],
               ['impact_type_other', 4],
               ['impact_type_recon', 5],
               ['impact_type_user', 6],

            ]
        );
    }
    
    unless (CIF::IDMEF::Linkage::LinkageCategory->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'CIF::IDMEF::Linkage::LinkageCategory',
            [
               ['linkage_category_hard_link', 1],
               ['linkage_category_mount_point', 2],
               ['linkage_category_reparse_point', 3],
               ['linkage_category_shortcut', 4],
               ['linkage_category_stream', 5],
               ['linkage_category_symbolic_link', 6],

            ]
        );
    }
    
    unless (CIF::IDMEF::Action::ActionCategory->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'CIF::IDMEF::Action::ActionCategory',
            [
               ['action_category_block_installed', 1],
               ['action_category_notification_sent', 2],
               ['action_category_other', 3],
               ['action_category_taken_offline', 4],

            ]
        );
    }
    
    unless (CIF::IDMEF::AdditionalData::AdditionaldataType->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'CIF::IDMEF::AdditionalData::AdditionaldataType',
            [
               ['additionaldata_type_boolean', 1],
               ['additionaldata_type_byte', 2],
               ['additionaldata_type_byte_string', 3],
               ['additionaldata_type_character', 4],
               ['additionaldata_type_date_time', 5],
               ['additionaldata_type_integer', 6],
               ['additionaldata_type_ntpstamp', 7],
               ['additionaldata_type_portlist', 8],
               ['additionaldata_type_real', 9],
               ['additionaldata_type_string', 10],
               ['additionaldata_type_xml', 11],

            ]
        );
    }
    
    unless (CIF::IDMEF::Checksum::ChecksumAlgorithm->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'CIF::IDMEF::Checksum::ChecksumAlgorithm',
            [
               ['checksum_algorithm_CRC_32', 1],
               ['checksum_algorithm_Gost', 2],
               ['checksum_algorithm_Haval', 3],
               ['checksum_algorithm_MD4', 4],
               ['checksum_algorithm_MD5', 5],
               ['checksum_algorithm_SHA1', 6],
               ['checksum_algorithm_SHA2_256', 7],
               ['checksum_algorithm_SHA2_384', 8],
               ['checksum_algorithm_SHA2_512', 9],
               ['checksum_algorithm_Tiger', 10],

            ]
        );
    }
    
    unless (CIF::IDMEF::Target::YesNoType->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'CIF::IDMEF::Target::YesNoType',
            [
               ['yes_no_type_no', 1],
               ['yes_no_type_unknown', 2],
               ['yes_no_type_yes', 3],

            ]
        );
    }
    
    unless (CIF::IDMEF::Permission::FilePermission->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'CIF::IDMEF::Permission::FilePermission',
            [
               ['file_permission_changePermissions', 1],
               ['file_permission_delete', 2],
               ['file_permission_execute', 3],
               ['file_permission_executeAs', 4],
               ['file_permission_noAccess', 5],
               ['file_permission_read', 6],
               ['file_permission_search', 7],
               ['file_permission_takeOwnership', 8],
               ['file_permission_write', 9],

            ]
        );
    }
    
    unless (CIF::IDMEF::AdditionalData->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::AdditionalData',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_BOOL(), 
                    '_boolean', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_BYTES(), 
                    '_byte', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'character', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT64(), 
                    'date_time', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    '_integer', 5, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'ntpstamp', 6, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::UnspecifiedType', 
                    'portlist', 7, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_DOUBLE(), 
                    'real', 8, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    '_string', 9, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::UnspecifiedType', 
                    'byte_string', 10, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::Xmltext', 
                    'xml', 11, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'CIF::IDMEF::AdditionalData::AdditionaldataType', 
                    'type', 12, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'meaning', 13, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::ToolAlert->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::ToolAlert',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'name', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'command', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::IDMEF::Alertident', 
                    'alertident', 3, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::Impact->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::Impact',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'CIF::IDMEF::Impact::ImpactSeverity', 
                    'severity', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'CIF::IDMEF::Impact::ImpactCompletion', 
                    'completion', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'CIF::IDMEF::Impact::ImpactType', 
                    'type', 3, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::Process->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::Process',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'name', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'pid', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'path', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'arg', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'env', 5, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'ident', 6, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::UserId->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::UserId',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'name', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'number', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'CIF::IDMEF::UserId::IdType', 
                    'type', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'tty', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'ident', 5, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::Address->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::Address',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'address', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'netmask', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'vlan_num', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'ident', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'vlan_name', 5, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'CIF::IDMEF::Address::AddressCategory', 
                    'category', 6, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::WebService->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::WebService',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::UnspecifiedType', 
                    'url', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'cgi', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'http_method', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'arg', 4, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::Alert->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::Alert',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::Analyzer', 
                    '_Analyzer', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::TimeWithNtpstamp', 
                    'CreateTime', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::TimeWithNtpstamp', 
                    'DetectTime', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::TimeWithNtpstamp', 
                    'AnalyzerTime', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::IDMEF::Source', 
                    '_Source', 5, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::IDMEF::Target', 
                    '_Target', 6, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::Classification', 
                    '_Classification', 7, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::Assessment', 
                    '_Assessment', 8, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::ToolAlert', 
                    '_ToolAlert', 9, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::OverflowAlert', 
                    '_OverflowAlert', 10, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::CorrelationAlert', 
                    '_CorrelationAlert', 11, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::IDMEF::AdditionalData', 
                    '_AdditionalData', 12, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'messageid', 13, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::UnspecifiedType->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::UnspecifiedType',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'baseObjectType', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_BYTES(), 
                    'object', 2, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::Node->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::Node',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'location', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'name', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::Address', 
                    '_Address', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'ident', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'CIF::IDMEF::Node::NodeCategory', 
                    'category', 5, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::Target->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::Target',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::Node', 
                    '_Node', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::User', 
                    '_User', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::Process', 
                    '_Process', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::Service', 
                    '_Service', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::IDMEF::File', 
                    '_File', 5, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'CIF::IDMEF::Target::YesNoType', 
                    'decoy', 6, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'ident', 7, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    '_interface', 8, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::Alertident->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::Alertident',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'analyzerid', 1, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::Confidence->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::Confidence',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::Confidence::ConfidenceRating', 
                    'rating', 1, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::Xmltext->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::Xmltext',
            [

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::Checksum->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::Checksum',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'value', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'key', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::Checksum::ChecksumAlgorithm', 
                    'algorithm', 3, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::Permission->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::Permission',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::Permission::FilePermission', 
                    'perms', 1, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::OverflowAlert->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::OverflowAlert',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'program', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'size', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::UnspecifiedType', 
                    'buffer', 3, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::User->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::User',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::IDMEF::UserId', 
                    '_UserId', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'ident', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'CIF::IDMEF::User::UserCategory', 
                    'category', 3, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::Reference->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::Reference',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'name', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'url', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'CIF::IDMEF::Reference::ReferenceOrigin', 
                    'origin', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'meaning', 4, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::Classification->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::Classification',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::IDMEF::Reference', 
                    '_Reference', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'text', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'ident', 3, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::IDMEFMessage->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::IDMEFMessage',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_DOUBLE(), 
                    'version', 1, 20120628
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::Alert', 
                    '_Alert', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::Heartbeat', 
                    '_Heartbeat', 3, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::Assessment->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::Assessment',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::Impact', 
                    '_Impact', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::IDMEF::Action', 
                    '_Action', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::Confidence', 
                    '_Confidence', 3, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::CorrelationAlert->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::CorrelationAlert',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'name', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::IDMEF::Alertident', 
                    'alertident', 2, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::Heartbeat->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::Heartbeat',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::Analyzer', 
                    '_Analyzer', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::TimeWithNtpstamp', 
                    'CreateTime', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'HeartbeatInterval', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::TimeWithNtpstamp', 
                    'AnalyzerTime', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::IDMEF::AdditionalData', 
                    '_AdditionalData', 5, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'messageid', 6, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::Inode->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::Inode',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'change_time', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'number', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'major_device', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'minor_device', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'c_major_device', 5, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'c_minor_device', 6, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::File->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::File',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'name', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'path', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT64(), 
                    'create_time', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT64(), 
                    'modify_time', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT64(), 
                    'access_time', 5, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'data_size', 6, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'disk_size', 7, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::IDMEF::FileAccess', 
                    '_FileAccess', 8, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::IDMEF::Linkage', 
                    '_Linkage', 9, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::Inode', 
                    '_Inode', 10, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::IDMEF::Checksum', 
                    '_Checksum', 11, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'fstype', 12, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'ident', 13, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'file_type', 14, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::File::FileCategory', 
                    'category', 15, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::Service->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::Service',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'name', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'port', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::UnspecifiedType', 
                    'portlist', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'protocol', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::SNMPService', 
                    '_SNMPService', 5, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::WebService', 
                    '_WebService', 6, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'ip_version', 7, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'ident', 8, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'iana_protocol_number', 9, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'iana_protocol_name', 10, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::Linkage->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::Linkage',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'name', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'path', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::File', 
                    '_File', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::Linkage::LinkageCategory', 
                    'category', 4, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::Analyzer->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::Analyzer',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::Node', 
                    '_Node', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::Process', 
                    '_Process', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_BYTES(), 
                    'Analyzer', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'version', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'ostype', 5, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'name', 6, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'analyzerid', 7, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'model', 8, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'manufacturer', 9, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    '_class', 10, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'osversion', 11, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::SNMPService->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::SNMPService',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'oid', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'messageProcessingModel', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'securityModel', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'securityName', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'securityLevel', 5, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'contextName', 6, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'contextEngineID', 7, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'command', 8, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::Action->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::Action',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'CIF::IDMEF::Action::ActionCategory', 
                    'category', 1, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::TimeWithNtpstamp->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::TimeWithNtpstamp',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'ntpstamp', 1, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::FileAccess->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::FileAccess',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::UserId', 
                    '_UserId', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(), 
                    'CIF::IDMEF::Permission', 
                    'permission', 2, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

    unless (CIF::IDMEF::Source->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'CIF::IDMEF::Source',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::Node', 
                    '_Node', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::User', 
                    '_User', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::Process', 
                    '_Process', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'CIF::IDMEF::Service', 
                    '_Service', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'ident', 5, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'CIF::IDMEF::Source::YesNoType', 
                    'spoofed', 6, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    '_interface', 7, undef
                ],

            ],
            { 'create_accessors' => 1, 'follow_best_practice' => 1,  }
        );
    }

}
1;
